import { GoogleGenAI } from '@google/genai';

// Initialize the Gemini client
const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

export async function analyzeWebDiff(url, diffData) {
  const systemInstruction = `You are an automated DevSecOps Incident Response Analyst integrated within a corporate Security Operations Center (SOC) framework. Your sole purpose is to audit raw code differences generated by a background web scanner application to identify active website defacements, security compromises, or hidden exploit payload code insertions.

You must rigorously enforce these functional execution parameters:
1. Complete Objectivity: Do not use any warm introductions, conversational pleasantries, greetings, or closure signatures. Do not say "Here is my evaluation" or "I can assist with that". Start typing technical evaluations instantly.
2. Threat Classification Matrix: Analyze both structural HTML layouts and syntax indicators pointing to code lines removed (-) or lines added (+). Identify hidden inline iframes, unverified external scripts, cryptojacking modules, phishing forms, text defacements, or unwanted image overrides.
3. Clean Plain-Text Output Strategy: Do not under any circumstances output raw markdown styling parameters, bolding notation (**), text header hashtags (#), or backtick code gates (\`\`\`). Provide your structured output entirely using standard line breaks and plain paragraph spacing.`;

  const prompt = `ALERT: Web server content integrity mutation mismatch captured on monitoring system.
Target Inspected Endpoint URL: ${url}

Examine the following text modification array showcasing lines removed (-) and lines added (+):

---
${diffData}
---

Execute your security assessment guidelines. Map the details of the specific threat vector or text change, explain in simple terms what negative impacts it introduces to visitors, and provide a single concise plain-text action statement telling the site administrator how to address or remove the compromised lines.`;

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash',
    contents: prompt,
    config: {
      systemInstruction: systemInstruction,
      temperature: 0.1, // Keeps the response analytical and highly consistent
    },
  });

  return response.text;
}
